version: 2.1

orbs:
  python: circleci/python@0.3.2
  node: circleci/node@3.0.1
  aws-s3: circleci/aws-s3@1.0.16

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    resource_class: small
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - node/install:
          install-yarn: true
          node-version: lts
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build and render
          command: python3 build.py build
      - persist_to_workspace:
          root: build
          paths:
            - html

  deploy:
    docker:
      - image: cimg/python:3.7
    resource_class: small
    steps:
      - attach_workspace:
          at: build
      - aws-s3/sync:
          from: build/html
          to: s3://jwchong.com/hl
          arguments: |
            --exclude .buildinfo

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          context: AWS
          requires:
            - build
          filters:
            branches:
              only: master
